<h1> WORKING WITH DATA

>Nguyen Tran

George Washington University
Introduction to Health Data Science PUBH1142
February 16, 2026

### Import Packages

In [1]:
import numpy as np
import pandas as pd

## Task 1

<mark>*Task:*</mark> Select the `Vocation` column and assign it to the variable vocation. Confirm that the object assigned to vocation is a pandas series object. The `tail` function (with no arguments), prints the last five observations to the screen. Use the `tail` function to print the last five observations in vocation to the screen.

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/juanklopper/TutorialData/main/PUBH1142Chap0801.csv")
df.head()

,Name,DOB,Age,Vocation,Smoke,HR,sBP,CholesterolBefore,TAG,Survey,CholesterolAfter,Delta,Group
0,Dylan Patton,1981-10-07,43,Energy manager,0,47,145,1.2,1.2,1,0.7,0.5,Active
1,Sandra Howard,1993-01-27,53,Tax adviser,0,51,115,1.2,0.6,3,1.0,0.2,Active
2,Samantha Williams,1973-12-21,33,IT consultant,0,54,120,2.0,1.3,3,1.7,0.3,Active
3,Ashley Hensley,1981-12-01,43,"Nurse, children's",0,54,103,2.1,1.6,4,2.1,0.0,Active
4,Robert Wilson,1964-06-23,46,Clinical embryologist,0,61,138,2.8,2.1,5,2.8,0.0,Active

In [15]:
Vocation = df.Vocation
type(Vocation)

pandas.core.series.Series

In [17]:
Vocation.tail()

195            Sales professional, IT
196                         Paramedic
197    Chartered certified accountant
198                            Dancer
199                Theme park manager
Name: Vocation, dtype: object

## Task 2

<mark>*Task:*</mark> Print the `TAG` and the `Smoke` variables to the screen, but only for observations (rows) $10$ through $15$.

In [19]:
df.loc[10:15, ["TAG", "Smoke"]]

    TAG  Smoke
10  1.7      0
11  2.0      0
12  2.3      0
13  2.1      0
14  2.4      0
15  2.6      2

## Task 3

<mark> *Task:*</mark> The `to_list` method creates a Python list object. Use the `to_list` method to create a Python list object of the `Age` values for those that have a value in the `HR` (heart rate) column that is more than $72$. Print only the first $10$ values.

In [23]:
df.loc[df.HR > 72, "Age"].to_list()[:10]

[57, 52, 49, 70, 45, 53, 50, 33, 30, 44]

## Task 4

<mark>*Task:*</mark> Create a variable named selection that will select for all the observations who never smoked, as a heart rate, `HR`, less than $80$, and a systolic blood pressure, `sBP`, of less than $120$. Use this selection to create a numpy $n$-dimensional array of the `Age` and triacylglycerol, `TAG`, variable values.

In [27]:
selection = (df.Smoke==0) & (df.HR < 80) & (df.sBP < 120)
df.loc[selection, ['Age', 'TAG']].to_numpy

<bound method DataFrame.to_numpy of     Age  TAG
1    53  0.6
3    43  1.6
8    44  2.4
11   35  2.0
21   45  2.1
41   55  3.1>

## Task 5

<mark>*Task:*</mark> Create a new variable named `AgeHR` that is the product of the values in the variables `Age` and `HR`.

In [28]:
df['AgeHR'] = df.Age * df.HR

## Task 6

<mark>*Task:*</mark> Create a new variable in the dataframe called `HRLevel` from the `HR` column with intervals ($0,65$], ($65,78$], ($78,1000$) with labels `low`, `normal`, and `high` respectively.

In [29]:
df['HRLevel'] = pd.cut(df.HR, bins = [0, 65, 78, 1000], right=True, labels=['low', 'normal', 'high'])
df.HRLevel[:5]

0    low
1    low
2    low
3    low
4    low
Name: HRLevel, dtype: category
Categories (3, object): ['low' < 'normal' < 'high']

## Quiz Questions

1. ##### *How do you import the pandas library in Python?*
    You can import the pandas library in python using `import pandas as pd`.
---
2. ##### *How do you read a CSV file named `data.csv` into a pandas DataFrame?*
    You can read a CSV file named `data.csv` as a pandas DataFrame using `df = pd.read_csv("data.csv")` if the CSV file is in the same file.
---
3. ##### *How do you display the first $5$ rows of a DataFrame named `df`?*
    You can display the first 5 rows of a DataFrame naemd `df` with `df.head(:5)`.
---
4. ##### *How do you find the number of rows and columns in a DataFrame `df`?*
    You can find the numbers of rows and columns in a DataFrame `df` using `df.shape`.
---
5. ##### *How do you print the names of all the columns in a DataFrame `df`?*
    You can print the names of all the columns in a DataFrame `df` using `df.__dir__`.
---
6. ##### *How do you get the summary information of the DataFrame `df` including data types and non-null values?*
    You can get the summary information using `df.dtypes`.
---
7. ##### *How do you select only the rows in DataFrame `df` where the column `A` is greater than $5$?*
    You can do so by using `df.loc['A' > , 'A'].to_list()`.
---
8. ##### *How do you select the columns `A` and `B` from the DataFrame `df`?*
    You can select the columns with `df.['AB_columns'] = df.['A', 'B']`.
---
9. ##### *How do you rename the column `A` to `Alpha` in DataFrame `df`?*
    You can rename with `df.rename(columns={'A', 'Alpha'}, inplace=True)`.
---
10. ##### *How do you replace all occurrences of the value `999` in DataFrame `df` with `nan`?*
    You can replace all occurences of $999$ with `nan` with `df = pd.read_csv('df'), na_values=[999]`.
---
11. ##### *How do you drop all rows in DataFrame `df` that contain missing values?*
    You can drop these values with `df = df.dropna()`.
---
12. ##### *How do you fill all missing values in DataFrame `df` with `0`?*
    You can fill all missing values by using `df.fillna(0)`.
---
13. ##### *How do you calculate the mean of column A in DataFrame `df`?*
    You can calculate the mean with `A = A_column.to_numpy()` and `A_column.mean()`.
---
14. ##### *How do you create a new column `C` in DataFrame `df` that is the sum of columns `A` and `B`?*
    You can create a new column as the sum with ` df['C'] = df.A + df.B`.
---
15. ##### *How do you save the DataFrame `df` to a CSV file named `output.csv`? (Find the solution by searching the pandas documentation.)*
    You can save it with `df.to_csv("outside.csv", index=False)`.